artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  github_url: "https://api.github.com/user/repos?per_page=100"
  save_dir: artifacts/data_ingestion
  
data_transformation:
  root_dir: artifacts/data_transformation
  file_dir: artifacts/data_ingestion
  save_dir: artifacts/data_transformation