
artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  github_url: "https://api.github.com/user/repos?per_page=100"
  linkedin_url: https://github.com/appsbotta/DataSets/raw/refs/heads/main/linkedinData.zip
  local_data_file: artifacts/data_ingestion/data.zip
  save_dir: artifacts/data_ingestion
  
data_transformation:
  root_dir: artifacts/data_transformation
  file_dir: artifacts/data_ingestion
  save_dir: artifacts/data_transformation

prediction:
  folder_dir: artifacts/data_transformation